{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customers\",\"Orders\",\"Order Details\",\"Products\"]"
      }
    ],
    "culture": "en-ZA",
    "cultures": [
      {
        "name": "en-ZA",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "8260a6e8-4bb4-4301-a5bd-a20d0e7f84a2",
        "fromColumn": "OrderDate",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_207f1d4c-8537-43f7-a3fe-6cbbced5515d"
      },
      {
        "name": "1cdc17a2-001a-45fa-b5ee-7bff0a95db65",
        "fromColumn": "OrderId",
        "fromTable": "Order Details",
        "toColumn": "OrderId",
        "toTable": "Orders"
      },
      {
        "name": "cef30d79-f374-4652-b3de-9f190d4520cb",
        "fromColumn": "ProductId",
        "fromTable": "Order Details",
        "toColumn": "ProductId",
        "toTable": "Products"
      },
      {
        "name": "d8ac9c82-1a52-4091-95a9-50d1cb305f1a",
        "fromColumn": "CustomerId",
        "fromTable": "Orders",
        "toCardinality": "many",
        "toColumn": "CustomerId",
        "toTable": "Customers"
      }
    ],
    "sourceQueryCulture": "en-ZA",
    "tables": [
      {
        "name": "DateTableTemplate_443ccb3d-39dc-4736-98c1-32750daebc2a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "46693dfa-6e02-4094-9ac8-70f5b29265b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "06c433df-25b7-4ce2-8622-27671cbcbd20",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f6e6e0bf-8be5-498b-a230-3d9deba09d4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1e05ad43-dd87-4cab-a9ce-f0bb86372766",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "363c166e-ea2c-4a3c-9e2a-919eb3df574a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0fbd7257-cd3c-442e-99f7-988bc031fce1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b69cb346-3d41-42c7-ac0f-9bdcfdce69b9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "93c9de16-3d60-411e-8994-686188057de2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8b13a19e-4384-4ec1-9033-d69952be37a9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "465e1d45-fc92-4528-abfc-26d1b257c06e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "00d5cdfd-dfd5-4b2c-a5e8-68e3867838e9",
                "ordinal": 3
              }
            ],
            "lineageTag": "d802b128-a257-4ec5-af58-4d094d421110"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "65ff3509-9ac1-4b4c-9e99-e87e2a5a453b",
        "partitions": [
          {
            "name": "DateTableTemplate_443ccb3d-39dc-4736-98c1-32750daebc2a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "845dd56a-58fa-4896-a97a-48bf9a56f20c",
            "sourceColumn": "CustomerId",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ec0f0c6-22a0-4585-80dc-a6a096fc3c2b",
            "sourceColumn": "CustomerTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "787efdae-9ecf-4a05-978c-587e2c0dc00b",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "CellPhone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a82906d5-b6be-427f-a520-2d25cd6b07b3",
            "sourceColumn": "CellPhone",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d9da8821-e8dc-41d4-93c8-b9f6196a1ec4",
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac-my.sharepoint.com/personal/35804068_mynwu_ac_za/Documents/CMPG323_Project5/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Customers_Sheet = Source{[Item=\"Customers\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Customers_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerId\", Int64.Type}, {\"CustomerTitle\", type text}, {\"Name\", type text}, {\"CellPhone\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "OrderId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1721c4ea-94d1-4743-886b-e7ec75c146d0",
            "sourceColumn": "OrderId",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "90a97714-4b6a-467d-a027-97443c3138bb",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_207f1d4c-8537-43f7-a3fe-6cbbced5515d"
                },
                "isDefault": true,
                "relationship": "8260a6e8-4bb4-4301-a5bd-a20d0e7f84a2"
              }
            ]
          },
          {
            "name": "CustomerId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8c5bacb-23e2-43ae-b729-63f212a6c435",
            "sourceColumn": "CustomerId",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c59f1884-072d-499d-a806-e53d9bcd5fe1",
            "sourceColumn": "DeliveryAddress",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b861bd4-26fd-41a9-85c0-919d6c13e4bd",
            "sourceColumn": "DeliveryId",
            "summarizeBy": "none"
          },
          {
            "name": "City/Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfb3474b-2789-49e9-a551-597a4543ba4f",
            "sourceColumn": "City/Street",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecd34603-fd97-40f7-a15b-db17a88d6837",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b929cb87-86ae-4cdf-aba9-9d877abd009c",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61e62e3c-3271-497d-b502-eb109d54aab3",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "41da2732-930a-46b3-8e1b-d6542a3d5ac3",
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac-my.sharepoint.com/personal/35804068_mynwu_ac_za/Documents/CMPG323_Project5/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderId\", Int64.Type}, {\"OrderDate\", type any}, {\"CustomerId\", Int64.Type}, {\"DeliveryAddress\", type text}, {\"Column5\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column5\", \"DeliveryId\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"10/06/20923\",#date(2023, 6, 10),Replacer.ReplaceValue,{\"OrderDate\"}),",
                "    #\"Removed Alternate Rows\" = Table.AlternateRows(#\"Replaced Value\",3,2,14),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Alternate Rows\",{{\"OrderDate\", type date}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type1\",\"San Francisco California United States 94122\",\"San Francisco, California, United States, 94122\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Mesa Arizona United States 85204\",\"Mesa, Arizona, United States, 85204\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Camarillo California United States 93010\",\"Camarillo, California, United States, 93010\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Replaced Value3\", \"OrderId\", \"OrderId - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"OrderId\", \"OrderDate\", \"CustomerId\", \"DeliveryAddress\", \"OrderId - Copy\", \"DeliveryId\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"OrderId - Copy\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type2\",{{\"OrderId - Copy\", \"City/Street\"}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"City/Street\", \"City/Street - Copy\"),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Duplicated Column1\",{\"OrderId\", \"OrderDate\", \"CustomerId\", \"DeliveryAddress\", \"City/Street\", \"City/Street - Copy\", \"DeliveryId\"}),",
                "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Reordered Columns1\", \"City/Street - Copy\", \"City/Street - Copy - Copy\"),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Duplicated Column2\",{\"OrderId\", \"OrderDate\", \"CustomerId\", \"DeliveryAddress\", \"City/Street\", \"City/Street - Copy\", \"City/Street - Copy - Copy\", \"DeliveryId\"}),",
                "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Reordered Columns2\", \"City/Street - Copy - Copy\", \"City/Street - Copy - Copy - Copy\"),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Duplicated Column3\",{\"OrderId\", \"OrderDate\", \"CustomerId\", \"DeliveryAddress\", \"City/Street\", \"City/Street - Copy\", \"City/Street - Copy - Copy\", \"City/Street - Copy - Copy - Copy\", \"DeliveryId\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Reordered Columns3\",\"100041\",\"4 Steve Biko Street\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"100090\",\"Sann Francisco\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Sann Francisco\",\"San Francisco\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"100216\",\"Mesa\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"100146\",\"Camarillo\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"100069\",\"Omaha\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Replaced Value9\",{{\"City/Street - Copy\", \"State\"}}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Renamed Columns2\",\"100041\",\"Potchefstroom\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"100090\",\"Carlifonia\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"Carlifonia\",\"California\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"100216\",\"Arizona\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"100146\",\"California\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"100069\",\"Nebraska\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"100041\",\"South Africa\",Replacer.ReplaceText,{\"City/Street - Copy - Copy\"}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Replaced Value16\",{{\"City/Street - Copy - Copy\", \"Country\"}}),",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Renamed Columns3\",\"100090\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"100216\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"100146\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value20\" = Table.ReplaceValue(#\"Replaced Value19\",\"100069\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Replaced Value20\",{{\"City/Street - Copy - Copy - Copy\", \"PostalCode\"}}),",
                "    #\"Replaced Value21\" = Table.ReplaceValue(#\"Renamed Columns4\",\"100041\",\"2520\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value22\" = Table.ReplaceValue(#\"Replaced Value21\",\"100090\",\"94122\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value23\" = Table.ReplaceValue(#\"Replaced Value22\",\"100216\",\"85204\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value24\" = Table.ReplaceValue(#\"Replaced Value23\",\"100146\",\"93010\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value25\" = Table.ReplaceValue(#\"Replaced Value24\",\"100069\",\"68104\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value26\" = Table.ReplaceValue(#\"Replaced Value25\",\"San Francisco, California, United States, 94122\",\"San Francisco California United States 94122\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Replaced Value27\" = Table.ReplaceValue(#\"Replaced Value26\",\"Mesa, Arizona, United States, 85204\",\"Mesa Arizona United States 85204\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Replaced Value28\" = Table.ReplaceValue(#\"Replaced Value27\",\"Camarillo, California, United States, 93010\",\"Camarillo California United States 93010\",Replacer.ReplaceText,{\"DeliveryAddress\"}),",
                "    #\"Replaced Value29\" = Table.ReplaceValue(#\"Replaced Value28\",\"100083\",\"Medford\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value30\" = Table.ReplaceValue(#\"Replaced Value29\",\"100153\",\"Norman\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value31\" = Table.ReplaceValue(#\"Replaced Value30\",\"100202\",\"Anaheim\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value32\" = Table.ReplaceValue(#\"Replaced Value31\",\"100048\",\"Mount Vernon\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value33\" = Table.ReplaceValue(#\"Replaced Value32\",\"100055\",\"Laurel\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value34\" = Table.ReplaceValue(#\"Replaced Value33\",\"100209\",\"Portland\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value35\" = Table.ReplaceValue(#\"Replaced Value34\",\"100160\",\"Philadelphia\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value36\" = Table.ReplaceValue(#\"Replaced Value35\",\"100111\",\"New York City\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value37\" = Table.ReplaceValue(#\"Replaced Value36\",\"100097\",\"New York City\",Replacer.ReplaceText,{\"City/Street\"}),",
                "    #\"Replaced Value38\" = Table.ReplaceValue(#\"Replaced Value37\",\"100097\",\"New York\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value39\" = Table.ReplaceValue(#\"Replaced Value38\",\"100111\",\"New York\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value40\" = Table.ReplaceValue(#\"Replaced Value39\",\"100048\",\"New York\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value41\" = Table.ReplaceValue(#\"Replaced Value40\",\"100160\",\"Pennsylvania\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value42\" = Table.ReplaceValue(#\"Replaced Value41\",\"100209\",\"Oregon\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value43\" = Table.ReplaceValue(#\"Replaced Value42\",\"100055\",\"Maryland\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value44\" = Table.ReplaceValue(#\"Replaced Value43\",\"100202\",\"California\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value45\" = Table.ReplaceValue(#\"Replaced Value44\",\"100153\",\"Oklahoma\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value46\" = Table.ReplaceValue(#\"Replaced Value45\",\"100083\",\"Oregon\",Replacer.ReplaceText,{\"State\"}),",
                "    #\"Replaced Value47\" = Table.ReplaceValue(#\"Replaced Value46\",\"100083\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value48\" = Table.ReplaceValue(#\"Replaced Value47\",\"100153\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value49\" = Table.ReplaceValue(#\"Replaced Value48\",\"100202\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value50\" = Table.ReplaceValue(#\"Replaced Value49\",\"100048\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value51\" = Table.ReplaceValue(#\"Replaced Value50\",\"100055\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value52\" = Table.ReplaceValue(#\"Replaced Value51\",\"100209\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value53\" = Table.ReplaceValue(#\"Replaced Value52\",\"100160\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value54\" = Table.ReplaceValue(#\"Replaced Value53\",\"100111\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value55\" = Table.ReplaceValue(#\"Replaced Value54\",\"100097\",\"United States\",Replacer.ReplaceText,{\"Country\"}),",
                "    #\"Replaced Value56\" = Table.ReplaceValue(#\"Replaced Value55\",\"100083\",\"97504\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value57\" = Table.ReplaceValue(#\"Replaced Value56\",\"100153\",\"73071\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value58\" = Table.ReplaceValue(#\"Replaced Value57\",\"100202\",\"92804\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value59\" = Table.ReplaceValue(#\"Replaced Value58\",\"100048\",\"10550\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value60\" = Table.ReplaceValue(#\"Replaced Value59\",\"100055\",\"20707\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value61\" = Table.ReplaceValue(#\"Replaced Value60\",\"100209\",\"97206\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value62\" = Table.ReplaceValue(#\"Replaced Value61\",\"100160\",\"19134\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value63\" = Table.ReplaceValue(#\"Replaced Value62\",\"100111\",\"10035\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value64\" = Table.ReplaceValue(#\"Replaced Value63\",\"100097\",\"10009\",Replacer.ReplaceText,{\"PostalCode\"}),",
                "    #\"Replaced Value65\" = Table.ReplaceValue(#\"Replaced Value64\",\"Potchefstroom\",\"North West\",Replacer.ReplaceText,{\"State\"})",
                "in",
                "    #\"Replaced Value65\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Order Details",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "OrderDetailsId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74c4464b-44ea-4188-ba38-78378185b4b1",
            "sourceColumn": "OrderDetailsId",
            "summarizeBy": "none"
          },
          {
            "name": "OrderId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c02e64a5-3576-4a1f-8a0c-97816e43a746",
            "sourceColumn": "OrderId",
            "summarizeBy": "none"
          },
          {
            "name": "ProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5f16f27-12a3-4893-ad3e-3f75c8c65deb",
            "sourceColumn": "ProductId",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a606521c-313b-473f-8560-162966281bc0",
            "sourceColumn": "Quantity",
            "summarizeBy": "none"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "92559bb8-6900-4ffa-ba7d-337475de5927",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalDiscount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Order Details'[Quantity] * 'Order Details'[Discount] ",
            "isDataTypeInferred": true,
            "lineageTag": "c3c2f93a-188a-4a81-8b09-8347c56a31ed",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "8d64eaaf-11e4-4624-aa33-32668eabfaa2",
        "measures": [
          {
            "name": "Sum of UnitsInStock minus Sum of Quantity",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('Products'[UnitsInStock]) - SUM('Order Details'[Quantity])"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalSubtraction",
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "lineageTag": "ba70a154-f0b6-4d2a-83f0-6d11a0c1ea50"
          }
        ],
        "partitions": [
          {
            "name": "Order Details",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac-my.sharepoint.com/personal/35804068_mynwu_ac_za/Documents/CMPG323_Project5/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    #\"Order Details_Sheet\" = Source{[Item=\"Order Details\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Order Details_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderDetailsID\", Int64.Type}, {\"OrderId\", Int64.Type}, {\"ProductId\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"Discount\", type number}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"OrderDetailsID\", \"OrderDetailsId\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b743fbfd-13a6-41c1-9ae6-4ccc69249ad9",
            "sourceColumn": "ProductId",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcfeb8d3-e95e-48a6-bc8e-d1a4428d8cc6",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d314e6b9-b4e5-47a1-b902-2c80c978000f",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "UnitsInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84943bee-2239-4c30-a340-b0c84f56a0ed",
            "sourceColumn": "UnitsInStock",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0ac7fd34-7440-49a6-a527-ffac0e21887e",
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://nwuac-my.sharepoint.com/personal/35804068_mynwu_ac_za/Documents/CMPG323_Project5/CMPG323%20EcoPower%20Logistics%20Data.xlsx\"), null, true),",
                "    Products_Sheet = Source{[Item=\"Products\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Products_Sheet,{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type any}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"ProductId\"}, {\"Column2\", \"ProductName\"}, {\"Column3\", \"Category\"}, {\"Column4\", \"UnitsInStock\"}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Renamed Columns\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Removed Blank Rows\",1),",
                "    #\"Removed Alternate Rows\" = Table.AlternateRows(#\"Removed Top Rows\",16,1,39),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Alternate Rows\",{{\"ProductId\", Int64.Type}, {\"UnitsInStock\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_207f1d4c-8537-43f7-a3fe-6cbbced5515d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f058b0d4-c3c7-449b-aab3-0bcbc960737b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "59d0ecd1-570f-4dc4-b3be-39d662ffe289",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9290a69d-46d7-4924-b7f2-eca9ea6a8c70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8b02dbd6-a76b-474d-857a-c14abe1df937",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "74c43452-139e-4dfd-acc4-9bac84449230",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6c1fc6f2-bd6a-4800-af3c-654e426534f7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9770b2d9-f1ca-4b8b-877a-a2169562f02b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "48fefed4-29b0-44b3-9e38-45b84926a659",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "578d9f4e-f134-4335-b4fd-dd3652caa913",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "85774101-4d97-4dd6-b865-8b3e0305a4c1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d91a9b19-ac67-40bc-9717-505bca7e2a63",
                "ordinal": 3
              }
            ],
            "lineageTag": "e9e8d388-25f3-4968-96ce-9e1c4c64cfe5"
          }
        ],
        "isHidden": true,
        "lineageTag": "7fe42d72-a545-4bab-857c-9c194705e219",
        "partitions": [
          {
            "name": "LocalDateTable_207f1d4c-8537-43f7-a3fe-6cbbced5515d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[OrderDate])), 1, 1), Date(Year(MAX('Orders'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}